// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Issue struct {
	ID          uuid.UUID      `json:"id"`
	Description sql.NullString `json:"description"`
	Priority    int32          `json:"priority"`
	StartDate   sql.NullTime   `json:"start_date"`
	TargetDate  sql.NullTime   `json:"target_date"`
	CreatedByID uuid.UUID      `json:"created_by_id"`
	ProjectID   uuid.UUID      `json:"project_id"`
	StateID     uuid.NullUUID  `json:"state_id"`
}

type Project struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
}

type State struct {
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Color       sql.NullString `json:"color"`
	Slug        string         `json:"slug"`
	CreatedByID uuid.UUID      `json:"created_by_id"`
	ProjectID   uuid.UUID      `json:"project_id"`
	WorkspaceID uuid.UUID      `json:"workspace_id"`
}

type User struct {
	ID       uuid.UUID      `json:"id"`
	Username string         `json:"username"`
	Email    sql.NullString `json:"email"`
}

type Workspace struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	CreatedByID uuid.UUID `json:"created_by_id"`
}
